### ISSUE TITLE
Version solving failed

### ISSUE THREAD

**Issue by makorne** [ftauth/sdk-dart#1]
```
$ cd sdk-dart/ftauth_flutter/example
$ flutter pub get
Because every version of flutter from sdk depends on meta 1.3.0 and every version of ftauth_jwt from path depends on meta ^1.7.0, flutter from sdk is incompatible with ftauth_jwt from path.
And because every version of ftauth_flutter from path depends on ftauth from path which depends on ftauth_jwt from path, flutter from sdk is incompatible with ftauth_flutter from path.
So, because ftauth_example depends on both flutter any from sdk and ftauth_flutter from path, version solving failed.
Running "flutter pub get" in example...                                 
pub get failed (1; So, because ftauth_example depends on both flutter any from sdk and ftauth_flutter from path, version solving failed.)
```

Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (6 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
Linux fedora 5.13.8-200.fc34.x86_64 #1 SMP Wed Aug 4 19:59:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

And please check why https://ftauth.io  is Not found.

**Comment by dnys1** [comment]
Lots of changes recently - should be resolved now. Sorry for that and thanks for playing with it! I've updated the examples [here](https://github.com/ftauth/sdk-dart/tree/main/example) if you're still interested.
